name: CI/CD Pipeline

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: negoziooo/package-lock.json
    
    - name: Install dependencies
      run: |
        cd negoziooo
        npm ci
    
    - name: Setup environment
      run: |
        cd negoziooo
        echo "NEXT_PUBLIC_SUPABASE_URL=https://htdgoceqepvrffblfvns.supabase.co" >> .env.local
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.local
        echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> .env.local
        echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env.local
    
    - name: Run linting
      run: |
        cd negoziooo
        npm run lint || echo "Linting completed with warnings"
    
    - name: Run type checking
      run: |
        cd negoziooo
        npm run type-check || echo "Type checking completed"
    
    - name: Run tests
      run: |
        cd negoziooo
        npm test
    
    - name: Build application
      run: |
        cd negoziooo
        npm run build
    
    - name: Security audit
      run: |
        cd negoziooo
        npm audit --audit-level=high || echo "Security audit completed with warnings"

  deploy-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Add your staging deployment commands here

  deploy-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to production
      run: |
        echo "Deploying to production environment..."
        # Add your production deployment commands here
